spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springapp
    username: Mohamed
    password: Mashy1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    azure:
      eventhubs:
        connection-string: Endpoint=sb://employees-space.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=EqJako2UkXXio2Hqkxpt5GScKDXgczVoSdWLh9/OsS8=
        processor:
          checkpoint-store:
            account-name: employeesstorage
            account-key: BJanT7viZEuFA14zg4FkVVRbNfV6WF8N+S9+HbySxm4gqjEuKMqN7DMhVFq2s2RiNxGZ9GUd6OfU+AStUskCiQ==
            container-name: changeevents
    stream:
      bindings:

        consume-in-0:
          destination: employeeshub
          group: $Default



    eventhubs:
      bindings:
        consume-in-0:
          consumer:
            checkpoint:
              mode: MANUAL
      function:
        definition: consume;


      poller:
        initial-delay: 0
        fixed-delay: 1000


server:
  port: 8082