spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/springapp
    username: Mohamed
    password: Mashy1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    azure:
      eventhubs:
        connection-string:
        processor:
          checkpoint-store:
            account-name: messagequeuestorage
            account-key: 4fc9Rsqn2RZUQJuRthYUU99TXkbLTEdAdSJWcmWF+IU6Jzbpkyl5/9GYQwSorXzaYq1k/jZaOPKl+AStrsiDvg==
            container-name: topic
    stream:
      bindings:

        consume-in-0:
          destination: messagequeuehub
          group: consumer1



      eventhubs:
        bindings:
          consume-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      function:
        definition: consume;


      poller:
        initial-delay: 0
        fixed-delay: 1000